#!/usr/bin/env python3
"""
Software Forge — AI Distro's code generation and project scaffolding engine.

Capabilities:
  1. Generate standalone scripts (Python, Bash, Rust)
  2. Scaffold full projects (Flask web apps, CLI tools, systemd services)
  3. Fix and iterate on existing code
  4. Auto-register generated tools as dynamic skills
  5. Sandboxed execution with output capture

Uses the local LLM (brain.py) for code generation and validates output
before registering as a new skill.
"""
import json
import os
import stat
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

# Directories
CUSTOM_TOOLS_DIR = Path(os.path.expanduser("~/AI_Distro/tools/agent/custom"))
DYNAMIC_SKILLS_DIR = Path(os.path.expanduser("~/AI_Distro/src/skills/dynamic"))
PROJECTS_DIR = Path(os.path.expanduser("~/ai-distro-projects"))
BRAIN_PATH = Path(os.path.dirname(__file__)) / "brain.py"


# ── Code Generation via LLM ──────────────────────────────────────────────

def generate_code_with_llm(description, language="python"):
    """Ask the brain to generate code for a given description."""
    prompt = textwrap.dedent(f"""\
        Write a complete, working {language} program that does the following:
        {description}

        Requirements:
        - The code must be complete and runnable
        - Include proper error handling
        - Include a main entry point
        - Use standard library modules where possible
        - Do NOT include any markdown formatting, just raw code
        - Do NOT include ```python or ``` markers

        Output ONLY the code, nothing else.
    """)

    try:
        result = subprocess.run(
            [sys.executable, str(BRAIN_PATH), prompt],
            capture_output=True, text=True, timeout=60
        )
        if result.returncode == 0:
            output = result.stdout.strip()
            # The brain returns JSON; extract the payload
            try:
                data = json.loads(output)
                code = data.get("payload", output)
                # Clean any markdown artifacts
                code = _clean_code(code)
                return code
            except json.JSONDecodeError:
                return _clean_code(output)
    except Exception:
        pass
    return None


def _clean_code(code):
    """Remove markdown code fences if present."""
    lines = code.strip().split("\n")
    # Remove leading/trailing ``` markers
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines)


# ── Project Templates ─────────────────────────────────────────────────────

TEMPLATES = {
    "script": {
        "python": textwrap.dedent("""\
            #!/usr/bin/env python3
            \"\"\"
            {name} — Generated by AI Distro Software Forge
            {description}
            \"\"\"
            import sys
            import json

            def main():
                {body}

            if __name__ == "__main__":
                main()
        """),
        "bash": textwrap.dedent("""\
            #!/bin/bash
            # {name} — Generated by AI Distro Software Forge
            # {description}
            set -euo pipefail

            main() {{
                {body}
            }}

            main "$@"
        """),
    },
    "flask_app": textwrap.dedent("""\
        #!/usr/bin/env python3
        \"\"\"
        {name} — Web Application Generated by AI Distro Software Forge
        {description}
        \"\"\"
        from flask import Flask, render_template_string, jsonify, request

        app = Flask(__name__)

        HTML_TEMPLATE = \"\"\"
        <!DOCTYPE html>
        <html>
        <head><title>{name}</title>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; max-width: 800px;
                   margin: 40px auto; padding: 20px; background: #1a1a2e;
                   color: #eee; }}
            h1 {{ color: #e94560; }}
            .card {{ background: #16213e; padding: 20px; border-radius: 12px;
                    margin: 10px 0; }}
        </style>
        </head>
        <body>
            <h1>{name}</h1>
            <div class="card"><p>{description}</p></div>
        </body>
        </html>
        \"\"\"

        @app.route("/")
        def index():
            return render_template_string(HTML_TEMPLATE)

        @app.route("/api/status")
        def api_status():
            return jsonify({{"status": "running", "app": "{name}"}})

        {routes}

        if __name__ == "__main__":
            app.run(host="0.0.0.0", port=5000, debug=True)
    """),
    "systemd_service": textwrap.dedent("""\
        [Unit]
        Description={name} - {description}
        After=network.target

        [Service]
        Type=simple
        User={user}
        WorkingDirectory={workdir}
        ExecStart={exec_start}
        Restart=on-failure
        RestartSec=5
        Environment=PYTHONUNBUFFERED=1

        [Install]
        WantedBy=multi-user.target
    """),
}


# ── Core Operations ───────────────────────────────────────────────────────

def create_script(name, description, language="python", code=None):
    """Create a standalone script with optional LLM-generated code."""
    CUSTOM_TOOLS_DIR.mkdir(parents=True, exist_ok=True)

    if not code:
        code = generate_code_with_llm(description, language)
        if not code:
            # Fallback: use template with placeholder
            body = f'print("TODO: {description}")'
            code = TEMPLATES["script"][language].format(
                name=name, description=description, body=body
            )

    # Determine extension
    ext = {"python": ".py", "bash": ".sh", "rust": ".rs"}.get(language, ".py")
    script_path = CUSTOM_TOOLS_DIR / f"{name}{ext}"

    with open(script_path, "w") as f:
        f.write(code)

    # Make executable
    script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC)

    return str(script_path)


def create_project(name, project_type, description):
    """Scaffold a complete project directory."""
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    project_dir = PROJECTS_DIR / name

    if project_dir.exists():
        return {"status": "error", "message": f"Project '{name}' already exists at {project_dir}"}

    project_dir.mkdir(parents=True)

    if project_type == "flask":
        # Create Flask web app
        app_code = TEMPLATES["flask_app"].format(
            name=name, description=description, routes=""
        )
        (project_dir / "app.py").write_text(app_code)
        (project_dir / "requirements.txt").write_text("flask>=3.0\ngunicorn>=21.2\n")
        (project_dir / "README.md").write_text(f"# {name}\n\n{description}\n\nGenerated by AI Distro Software Forge.\n\n## Run\n```bash\npip install -r requirements.txt\npython app.py\n```\n")

    elif project_type == "cli":
        # Create CLI tool
        code = generate_code_with_llm(
            f"A command-line tool that {description}. Use argparse for argument parsing.",
            "python"
        ) or TEMPLATES["script"]["python"].format(
            name=name, description=description,
            body='print("CLI tool scaffolded. Add your logic here.")'
        )
        (project_dir / f"{name}.py").write_text(code)
        (project_dir / "README.md").write_text(f"# {name}\n\n{description}\n")

    elif project_type == "service":
        # Create a systemd service with a Python daemon
        daemon_code = TEMPLATES["script"]["python"].format(
            name=name, description=description,
            body=textwrap.dedent("""\
                import time
                print(f"Service {name} started.")
                while True:
                    # Main service loop
                    time.sleep(60)""").replace("\n", "\n    ")
        )
        (project_dir / "daemon.py").write_text(daemon_code)

        user = os.environ.get("USER", "root")
        service_unit = TEMPLATES["systemd_service"].format(
            name=name, description=description,
            user=user, workdir=str(project_dir),
            exec_start=f"/usr/bin/python3 {project_dir}/daemon.py"
        )
        (project_dir / f"{name}.service").write_text(service_unit)
        (project_dir / "README.md").write_text(
            f"# {name}\n\n{description}\n\n## Install\n```bash\nsudo cp {name}.service /etc/systemd/system/\nsudo systemctl enable {name}\nsudo systemctl start {name}\n```\n"
        )
    else:
        # Generic project
        (project_dir / "main.py").write_text(
            f'#!/usr/bin/env python3\n"""{description}"""\nprint("Hello from {name}!")\n'
        )
        (project_dir / "README.md").write_text(f"# {name}\n\n{description}\n")

    return {"status": "ok", "path": str(project_dir), "type": project_type}


def register_as_skill(name, script_path, description):
    """Register a generated script as a dynamic AI Distro skill."""
    DYNAMIC_SKILLS_DIR.mkdir(parents=True, exist_ok=True)

    skill_def = {
        "name": name,
        "display_name": name.replace("_", " ").title(),
        "description": description or f"Custom tool: {name}",
        "category": "generated",
        "handler": {
            "type": "python_script",
            "path": script_path
        },
        "parameters": {
            "type": "object",
            "properties": {
                "input": {"type": "string", "description": "Input for the tool"}
            }
        },
        "tags": ["generated", "dynamic", "software-forge"]
    }

    skill_path = DYNAMIC_SKILLS_DIR / f"{name}.json"
    with open(skill_path, "w") as f:
        json.dump(skill_def, f, indent=2)

    return str(skill_path)


def execute_sandboxed(code, language="python", timeout=30):
    """Execute code in a sandboxed temporary environment."""
    ext = {"python": ".py", "bash": ".sh"}.get(language, ".py")
    interpreter = {"python": sys.executable, "bash": "/bin/bash"}.get(language, sys.executable)

    with tempfile.NamedTemporaryFile(suffix=ext, mode="w", delete=False) as tmp:
        tmp.write(code)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            [interpreter, tmp_path],
            capture_output=True, text=True, timeout=timeout,
            env={**os.environ, "AI_DISTRO_SANDBOX": "1"}
        )
        return {
            "status": "ok" if result.returncode == 0 else "error",
            "stdout": result.stdout[:4096],  # Cap output
            "stderr": result.stderr[:2048],
            "exit_code": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {"status": "error", "message": f"Script timed out after {timeout}s"}
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        os.unlink(tmp_path)


def fix_code(code, error_message, language="python"):
    """Ask the LLM to fix broken code given an error message."""
    prompt = textwrap.dedent(f"""\
        The following {language} code has an error:

        ```
        {code}
        ```

        The error is:
        {error_message}

        Fix the code. Output ONLY the corrected code, nothing else.
        Do NOT include any markdown formatting.
    """)
    return generate_code_with_llm(prompt, language)


# ── Main CLI Entry Point ──────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print(json.dumps({
            "status": "error",
            "message": "Usage: software_forge.py <command> [args]\n"
                       "Commands: create_script, create_project, execute, fix, generate"
        }))
        return

    cmd = sys.argv[1]

    if cmd == "create_script":
        # create_script <name> <description> [language]
        name = sys.argv[2] if len(sys.argv) > 2 else "untitled"
        desc = sys.argv[3] if len(sys.argv) > 3 else "A custom script"
        lang = sys.argv[4] if len(sys.argv) > 4 else "python"

        path = create_script(name, desc, lang)
        skill_path = register_as_skill(name, path, desc)
        print(json.dumps({
            "status": "ok",
            "message": f"Script created at {path} and registered as skill.",
            "script_path": path,
            "skill_path": skill_path
        }))

    elif cmd == "create_project":
        # create_project <name> <type> <description>
        name = sys.argv[2] if len(sys.argv) > 2 else "my_project"
        ptype = sys.argv[3] if len(sys.argv) > 3 else "generic"
        desc = sys.argv[4] if len(sys.argv) > 4 else "A new project"

        result = create_project(name, ptype, desc)
        print(json.dumps(result))

    elif cmd == "execute":
        # execute <code_or_json>
        payload = sys.argv[2] if len(sys.argv) > 2 else ""
        code = ""
        lang = "python"

        if payload.startswith("{"):
            try:
                data = json.loads(payload)
                code = data.get("code", "")
                lang = data.get("language", "python")
            except json.JSONDecodeError:
                code = payload
        else:
            code = payload

        if not code:
            print(json.dumps({"status": "error", "message": "No code provided."}))
            return

        result = execute_sandboxed(code, lang)

        # If execution failed, try to auto-fix
        if result["status"] == "error" and result.get("stderr"):
            fixed = fix_code(code, result["stderr"], lang)
            if fixed and fixed != code:
                retry = execute_sandboxed(fixed, lang)
                if retry["status"] == "ok":
                    result = retry
                    result["auto_fixed"] = True

        print(json.dumps(result))

    elif cmd == "generate":
        # generate <description> [language]
        desc = sys.argv[2] if len(sys.argv) > 2 else ""
        lang = sys.argv[3] if len(sys.argv) > 3 else "python"
        code = generate_code_with_llm(desc, lang)
        if code:
            print(json.dumps({"status": "ok", "code": code}))
        else:
            print(json.dumps({"status": "error", "message": "Code generation failed."}))

    elif cmd == "fix":
        # fix <code> <error>
        code = sys.argv[2] if len(sys.argv) > 2 else ""
        error = sys.argv[3] if len(sys.argv) > 3 else ""
        fixed = fix_code(code, error)
        if fixed:
            print(json.dumps({"status": "ok", "code": fixed}))
        else:
            print(json.dumps({"status": "error", "message": "Could not fix code."}))

    else:
        print(json.dumps({"status": "error", "message": f"Unknown command: {cmd}"}))


if __name__ == "__main__":
    main()
