import React, { useState } from 'react';
import { getEmails } from '../kernel/dataServices';
import { Star, ArrowLeft, MailOpen, Circle, ExternalLink } from 'lucide-react';

export const EmailApp: React.FC = () => {
    const emails = getEmails();
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const [signedIn, setSignedIn] = useState<boolean>(() => {
        if (typeof window === 'undefined') return false;
        return window.localStorage.getItem('mnemonicos_email_connected') === '1';
    });

    const [connecting, setConnecting] = useState<boolean>(false);

    const connectProvider = async (provider: 'gmail' | 'outlook') => {
        try {
            setConnecting(true);
            const res = await fetch('http://127.0.0.1:17842/api/provider/connect/start', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ target: 'email', provider })
            });
            const data = await res.json();

            if (data.status === 'pending' && data.auth_url) {
                // Open the actual OAuth URL generated by the Python backend
                window.open(data.auth_url, '_blank', 'width=600,height=800');

                // Poll for completion
                const pollInterval = setInterval(async () => {
                    try {
                        const statusRes = await fetch('http://127.0.0.1:17842/api/provider/connect/status?target=email');
                        const statusData = await statusRes.json();
                        if (statusData.status === 'connected') {
                            clearInterval(pollInterval);
                            window.localStorage.setItem('mnemonicos_email_connected', '1');
                            setSignedIn(true);
                            setConnecting(false);
                        } else if (statusData.status === 'error' || statusData.status === 'idle') {
                            clearInterval(pollInterval);
                            setConnecting(false);
                            console.error('OAuth failed or expired');
                        }
                    } catch (err) {
                        // ignore polling errors
                    }
                }, 2000);
            } else {
                setConnecting(false);
                console.error('Failed to start OAuth', data);
            }
        } catch (err) {
            setConnecting(false);
            console.error('API Error connecting provider', err);
        }
    };

    const selected = emails.find(e => e.id === selectedId);

    if (!signedIn) {
        return (
            <div className="h-full flex flex-col items-center justify-center gap-6 p-8">
                <div className="w-16 h-16 rounded-2xl bg-white/[0.05] border border-white/10 flex items-center justify-center">
                    <MailOpen className="w-8 h-8 text-white/40" />
                </div>
                <div className="text-center">
                    <h3 className="text-lg font-light text-white mb-2">Connect your email</h3>
                    <p className="text-sm text-white/40 max-w-xs mb-2">Sign in to securely sync your inbox through AI Distro.</p>
                    {connecting && <p className="text-xs text-cyan-400 animate-pulse">Waiting for authentication in browser...</p>}
                </div>
                <div className="space-y-2 w-full max-w-xs">
                    <button
                        onClick={() => connectProvider('gmail')}
                        disabled={connecting}
                        className="w-full flex items-center justify-center gap-3 px-4 py-3 bg-white/[0.06] border border-white/10 rounded-xl hover:bg-white/[0.1] transition-colors disabled:opacity-50"
                    >
                        <GoogleIcon />
                        <span className="text-sm text-white/70 font-medium">Sign in with Google</span>
                    </button>
                    <button
                        onClick={() => connectProvider('outlook')}
                        disabled={connecting}
                        className="w-full flex items-center justify-center gap-3 px-4 py-3 bg-white/[0.06] border border-white/10 rounded-xl hover:bg-white/[0.1] transition-colors disabled:opacity-50"
                    >
                        <MicrosoftIcon />
                        <span className="text-sm text-white/70 font-medium">Sign in with Microsoft</span>
                    </button>
                </div>
            </div>
        );
    }

    if (selected) {
        return (
            <div className="h-full overflow-y-auto flex flex-col">
                {/* Header */}
                <div className="flex items-center gap-3 px-5 py-4 border-b border-white/8">
                    <button
                        onClick={() => setSelectedId(null)}
                        className="p-1.5 rounded-lg hover:bg-white/10 transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4 text-white/50" />
                    </button>
                    <div className="flex-1 min-w-0">
                        <h3 className="text-sm font-medium text-white truncate">{selected.subject}</h3>
                        <div className="text-xs text-white/40">{selected.from} &lt;{selected.fromEmail}&gt;</div>
                    </div>
                    <span className="text-xs text-white/30">{selected.time}</span>
                </div>
                {/* Body */}
                <div className="flex-1 p-6">
                    <div className="text-sm text-white/70 whitespace-pre-wrap leading-relaxed">{selected.body}</div>
                </div>
                {/* Reply */}
                <div className="p-4 border-t border-white/8">
                    <div className="bg-white/[0.03] border border-white/8 rounded-xl p-3 text-xs text-white/30">
                        Click to reply...
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="h-full overflow-y-auto">
            <div className="px-5 py-4 border-b border-white/8 flex items-center justify-between">
                <h2 className="text-sm font-medium text-white/50 uppercase tracking-wider">Inbox</h2>
                <span className="text-xs text-white/30">{emails.filter(e => !e.read).length} unread</span>
            </div>
            {emails.length === 0 ? (
                <div className="h-[calc(100%-52px)] flex flex-col items-center justify-center gap-3 text-center px-8">
                    <MailOpen className="w-8 h-8 text-white/30" />
                    <p className="text-sm text-white/50">No synced mailbox data yet.</p>
                    <div className="flex gap-2">
                        <button onClick={() => window.open('https://mail.google.com', '_blank')} className="px-3 py-2 text-xs rounded-lg border border-white/10 bg-white/[0.04] hover:bg-white/[0.08] inline-flex items-center gap-1">
                            Open Gmail <ExternalLink className="w-3 h-3" />
                        </button>
                        <button onClick={() => window.open('https://outlook.live.com/mail/', '_blank')} className="px-3 py-2 text-xs rounded-lg border border-white/10 bg-white/[0.04] hover:bg-white/[0.08] inline-flex items-center gap-1">
                            Open Outlook <ExternalLink className="w-3 h-3" />
                        </button>
                    </div>
                </div>
            ) : (
                <div>
                    {emails.map(mail => (
                        <button
                            key={mail.id}
                            onClick={() => setSelectedId(mail.id)}
                            className={`w-full flex items-start gap-3 px-5 py-4 border-b border-white/5 text-left hover:bg-white/[0.04] transition-colors ${!mail.read ? 'bg-white/[0.02]' : ''
                                }`}
                        >
                            {/* Avatar */}
                            <div
                                className="w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold text-white shrink-0"
                                style={{ backgroundColor: stringToColor(mail.from) }}
                            >
                                {mail.from[0]}
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="flex items-center justify-between mb-0.5">
                                    <span className={`text-sm ${mail.read ? 'text-white/50' : 'text-white font-medium'}`}>{mail.from}</span>
                                    <span className="text-[10px] text-white/30 shrink-0 ml-2">{mail.time}</span>
                                </div>
                                <div className={`text-xs truncate ${mail.read ? 'text-white/35' : 'text-white/60'}`}>{mail.subject}</div>
                                <div className="text-xs text-white/25 truncate mt-0.5">{mail.preview}</div>
                            </div>
                            <div className="flex flex-col items-center gap-2 shrink-0 pt-1">
                                {!mail.read && <Circle className="w-2 h-2 fill-cyan-400 text-cyan-400" />}
                                {mail.starred && <Star className="w-3 h-3 fill-amber-400 text-amber-400" />}
                            </div>
                        </button>
                    ))}
                </div>
            )}
        </div>
    );
};

// OAuth brand icons (simplified SVG)
const GoogleIcon = () => (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
        <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z" fill="#4285F4" />
        <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853" />
        <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18A10.96 10.96 0 0 0 1 12c0 1.77.42 3.45 1.18 4.93l3.66-2.84z" fill="#FBBC05" />
        <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335" />
    </svg>
);

const MicrosoftIcon = () => (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
        <rect x="1" y="1" width="10" height="10" fill="#F25022" />
        <rect x="13" y="1" width="10" height="10" fill="#7FBA00" />
        <rect x="1" y="13" width="10" height="10" fill="#00A4EF" />
        <rect x="13" y="13" width="10" height="10" fill="#FFB900" />
    </svg>
);

function stringToColor(str: string): string {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    return `hsl(${Math.abs(hash % 360)}, 50%, 40%)`;
}
